Repository Markyjay/sunshine_squad_hackathon, pull requests merged in 2024-03, with the labels that each got.

#32 Create game-page files, add to routes, edit base
  appmanager/routes.py
  appmanager/static/css/style.css
  appmanager/static/js/game-page.js
  appmanager/templates/base.html
  appmanager/templates/game-page.html
Labels: Backend Framework

#33 fix merging issue
  appmanager/routes.py
  appmanager/server/articles.py
Labels: bug

#27 my branch
  appmanager/templates/base.html
Labels: Testing

#37 Article details
  .gitignore
  appmanager/__init__.py
  appmanager/routes.py
  appmanager/server/articles.py
  appmanager/templates/article-details.html
  appmanager/templates/home.html
  appmanager/utils/helper.py
  flask_session/2029240f6d1128be89ddc32729463129
  flask_session/79197d1aa29834ed550f8551e55e65b7
Labels: Design, Backend

#40 Added a function to display response messages according to the user mood
  appmanager/static/js/mood-index.js
Labels: JavaScript

#44 get articles with positivity
  .gitignore
  appmanager/routes.py
  appmanager/server/articles.py
  appmanager/server/demo_data.py
  appmanager/static/css/style.css
  appmanager/static/js/script.js
  appmanager/templates/base.html
  appmanager/templates/home.html
  flask_session/2029240f6d1128be89ddc32729463129
Labels: Backend

#45 delete outside border from the game board
  appmanager/static/css/style.css
  appmanager/templates/base.html
Labels: Feature Request

#47 fix styling for main page
  appmanager/static/css/style.css
  appmanager/templates/home.html
  flask_session/9f3a3aa26f66329793e4892a94fbbfe1
Labels: Design

#53 News Feed
  appmanager/static/css/style.css
  appmanager/templates/article-details.html
  appmanager/templates/base.html
  appmanager/templates/home.html
  flask_session/2029240f6d1128be89ddc32729463129
  flask_session/79197d1aa29834ed550f8551e55e65b7
Labels: Frontend

#54 deployment configuration
  Procfile
  requirements.txt
Labels: Deployment

#63 style the jokes page
  appmanager/routes.py
  appmanager/server/constants.py
  appmanager/server/demo_data.py
  appmanager/static/css/style.css
  appmanager/templates/gallery.html
  flask_session/3a225df20e6e03bb9269ab8434435b65
Labels: enhancement, Frontend, HTML, JavaScript, Frontend Framework

#82 Fixed minor spelling issues in the text on various pages
  appmanager/templates/base.html
  appmanager/templates/game-page.html
  appmanager/templates/home.html
Labels: HTML

#88 Updated game area
  appmanager/static/css/style.css
  appmanager/templates/game-page.html
  flask_session/2029240f6d1128be89ddc32729463129
  flask_session/faa75bc7a5ed13e94ad5968012adaee3
Labels: enhancement

#91 Update CSS styles and navigation links
  appmanager/static/css/style.css
  appmanager/templates/base.html
  appmanager/templates/contributors-page.html
  appmanager/templates/home.html
Labels: Design, CSS

#100 Renamed an HTML file to maintain consistency in file names
  appmanager/templates/mood-index.html
Labels: HTML
